buzzfeed_fetcher: ruby src/fetchers/buzzfeed_fetcher.rb
cnn_blog_fetcher: ruby src/fetchers/cnn_blog_fetcher.rb
defamer_fetcher: ruby src/fetchers/defamer_fetcher.rb
gawker_fetcher: ruby src/fetchers/gawker_fetcher.rb
giantbomb_fetcher: ruby src/fetchers/giantbomb_fetcher.rb
guardian_blogs_fetcher: ruby src/fetchers/guardian_blogs_fetcher.rb
huffpost_blogs_fetcher: ruby src/fetchers/huffpost_blogs_fetcher.rb
io9_fetcher: ruby src/fetchers/io9_fetcher.rb
jezebel_fetcher: ruby src/fetchers/jezebel_fetcher.rb
kotaku_fetcher: ruby src/fetchers/kotaku_fetcher.rb
nature_blog_fetcher: ruby src/fetchers/nature_blog_fetcher.rb
npr_two_way_fetcher: ruby src/fetchers/npr_two_way_fetcher.rb
nypost_fetcher: ruby src/fetchers/nypost_fetcher.rb
nytimes_lede_fetcher: ruby src/fetchers/nytimes_lede_fetcher.rb
r_funny_fetcher: ruby src/fetchers/r_funny_fetcher.rb
r_politics_fetcher: ruby src/fetchers/r_politics_fetcher.rb
tested_fetcher: ruby src/fetchers/tested_fetcher.rb
theblaze_fetcher: ruby src/fetchers/theblaze_fetcher.rb
thinkprogress_fetcher: ruby src/fetchers/thinkprogress_fetcher.rb
tmz_fetcher: ruby src/fetchers/tmz_fetcher.rb
upworthy_fetcher: ruby src/fetchers/upworthy_fetcher.rb