---
hackernews:
  name: Hacker News
  category: Geek
  default: false
theblaze:
  name: The Blaze
  category: Opinion - Conservative
  default: false
breitbart:
  name: Breitbart
  category: Opinion - Conservative
  default: false
alternet:
  name: Alternet
  category: Opinion - Progressive
  default: false
rawstory:
  name: The Raw Story
  category: Opinion - Progressive
  default: false
newsbusters:
  name: NewsBusters
  category: Opinion - Conservative
  default: false
faith_it:
  name: FaithIt
  category: Opinion - Conservative
  default: false
lifehacker:
  name: Lifehacker
  category: Geek
  default: false
daringfireball:
  name: Daring Fireball Links
  category: Geek
  default: false
macrumors:
  name: MacRumors
  category: Geek
  default: false
gizmodo:
  name: Gizmodo
  category: Geek
  default: false
valleywag:
  name: Valleywag
  category: Geek
  default: false
drudge_report:
  name: Drudge Report
  category: Opinion - Conservative
  default: false
free_republic:
  name: Free Republic
  category: Opinion - Conservative
  default: false
cns_news:
  name: CNS News
  category: Opinion - Conservative
  default: false
hot_air:
  name: HotAir
  category: Opinion - Conservative
  default: false
deadspin:
  name: Deadspin
  category: Sports
  default: false
sb_nation:
  name: SBNation
  category: Sports
  default: false
nypost:
  name: New York Post
  category: Opinion - Conservative
  default: false
huffpost_blogs:
  name: Huffington Post
  category: Opinion - Progressive
  default: false
thinkprogress:
  name: ThinkProgress
  category: Opinion - Progressive
  default: false
daily_kos:
  name: Daily Kos
  category: Opinion - Progressive
  default: false
distractify:
  name: Distractify
  category: Hypersensational
  default: false
mashable:
  name: Mashable
  category: Hypersensational
  default: false
sploid:
  name: Sploid
  category: Geek
  default: false
tmz:
  name: TMZ
  category: Entertainment
  default: false
giantbomb:
  name: Giant Bomb
  category: Geek
  default: false
kotaku:
  name: Kotaku
  category: Geek
  default: false
polygon:
  name: Polygon
  category: Geek
  default: false
buzzfeed:
  name: BuzzFeed
  category: Hypersensational
  default: true
pitchfork:
  name: Pitchfork
  category: Entertainment
  default: true
spin:
  name: Spin
  category: Entertainment
  default: false
thegloss:
  name: The Gloss
  category: Misc.
  default: false
mommyish:
  name: Mommyish
  category: Misc.
  default: false
mcsweenys:
  name: McSweeny's
  category: Misc.
  default: false
av_club:
  name: The A.V. Club
  category: Entertainment
  default: true
hollywood_reporter:
  name: The Hollywood Reporter
  category: Entertainment
  default: false
college_humor:
  name: CollegeHumor
  category: Bro
  default: false
the_chive:
  name: The Chive
  category: Bro
  default: false
cracked:
  name: Cracked
  category: Hypersensational
  default: true
viralnova:
  name: Viralnova
  category: Hypersensational
  default: false
bro_bible:
  name: BroBible
  category: Bro
  default: false
zergnet:
  name: ZergNet
  category: Hypersensational
  default: true
upworthy:
  name: Upworthy
  category: Hypersensational
  default: true
gawker:
  name: Gawker
  category: Hypersensational
  default: false
defamer:
  name: Defamer
  category: Entertainment
  default: false
uproxx:
  name: Uproxx
  category: Entertainment
  default: false
hitfix:
  name: HitFix
  category: Entertainment
  default: false
mental_floss:
  name: Mental Floss
  category: Hypersensational
  default: false
jezebel:
  name: Jezebel
  category: Entertainment
  default: true
io9:
  name: io9
  category: Geek
  default: true
tested:
  name: Tested
  category: Geek
  default: false
cnn_blog:
  name: CNN
  category: News
  default: false
guardian_blogs:
  name: The Guardian
  category: News
  default: false
business_insider:
  name: Business Insider
  category: Hypersensational
  default: true
fivethirtyeight:
  name: FiveThirtyEight
  category: News
  default: false
nature_blog:
  name: Nature
  category: Geek
  default: false
npr_two_way:
  name: NPR Two Way
  category: News
  default: false
the_daily_beast:
  name: The Daily Beast
  category: News
  default: false
npr:
  name: NPR
  category: News
  default: false
slate:
  name: Slate
  category: News
  rss_feeds: http://www.slate.com/all.fulltext.all.rss
nymag:
  name: New York Magazine
  category: Entertainment
  rss_feeds:
  - http://feeds.feedburner.com/nymag/intelligencer
  - http://feeds.feedburner.com/nymag/fashion
  - http://feeds.feedburner.com/nymag/grubstreet
  - http://feeds.feedburner.com/nymag/scienceofus
  - http://feeds.feedburner.com/nymag/vulture
nytimes:
  name: New York Times
  category: News
  default: true
latimes:
  name: Los Angeles Times
  category: News
  rss_feeds: http://www.latimes.com/rss2.0.xml
r_politics:
  name: r/politics
  category: Reddit
  default: false
  dead: true
r_funny:
  name: r/funny
  category: Reddit
  default: false
  dead: true
wired:
  name: Wired
  category: Geek
  default: false
  url: http://wired.com
foxnews:
  name: Fox News
  category: Opinion - Conservative
  default: false
  url: http://www.foxnews.com/
nytimes_lede:
  name: New York Times Lede
  category: News
  default: false
  dead: true
ryot:
  name: RYOT
  category: Hypersensational
  rss_feeds:
  - http://www.ryot.org/feed
time:
  name: TIME
  category: News
  rss_feeds:
  - http://newsfeed.time.com/feed/
  - http://swampland.time.com/feed/
  - http://techland.time.com/feed/
  - http://lightbox.time.com/feed/
  - http://lightbox.time.com/category/closeup/feed/
people:
  name: People
  category: Entertainment
  rss_feeds:
  - http://rss.people.com/web/people/rss/topheadlines/index.xml
  - http://rss.people.com/web/people/rss/photogalleries/index.xml
  - http://rss.people.com/web/people/rss/tvwatch/index.xml
  - http://rss.people.com/web/people/rss/pets/index.xml
msnbc:
  name: msnbc
  category: News
  rss_feeds:
  - http://www.msnbc.com/feeds/latest
vh1:
  name: VH1
  category: Entertainment
  rss_feeds:
  - http://blog.vh1.com/feed/
  - http://www.vh1.com/celebrity/feed/
  - http://www.bestweekever.tv/feed/
  - http://www.vh1.com/rss/news/today_on_vh1.jhtml
  - http://www.vh1.com/rss/news/movielatestcached.jhtml?partner=rssMozilla
hellogiggles:
  name: HelloGiggles
  category: Entertainment
  rss_feeds:
  - http://hellogiggles.com/feed
laughingsquid:
  name: Laughing Squid
  category: Entertainment
  rss_feeds:
  - http://feeds.laughingsquid.com/laughingsquid
zimbio:
  name: Zimbio
  category: Entertainment
  rss_feeds:
  - http://www.zimbio.com/rss
stylebistro:
  name: StyleBistro
  category: Entertainment
  rss_feeds:
  - http://www.stylebistro.com/rss
lonny:
  name: Lonny
  category: Entertainment
  rss_feeds:
  - http://www.lonny.com/rss
thedailywhat:
  name: The Daily What
  category: Entertainment
  rss_feeds:
  - http://thedailywh.at/feed/
accesshollywood:
  name: Access Hollywood
  category: Entertainment
  rss_feeds: http://feeds.accesshollywood.com/AccessHollywood/LatestNews
fastcompany:
  name: Fast Company
  category: Geek
  rss_feeds:
  - http://www.fastcompany.com/rss.xml
mtv:
  name: MTV
  category: Entertainment
  rss_feeds: http://www.mtv.com/news/feed/
mirror:
  name: Mirror
  category: News
  rss_feeds:
  - http://www.mirror.co.uk/rss.xml
theindependent:
  name: The Independent
  rss_feeds:
  - http://rss.feedsportal.com/c/266/f/3792/index.rss
  - http://rss.feedsportal.com/c/266/f/3800/index.rss
  - http://rss.feedsportal.com/c/266/f/3795/index.rss
  - http://rss.feedsportal.com/c/266/f/464881/index.rss
  - http://rss.feedsportal.com/c/266/f/3797/index.rss
  - http://rss.feedsportal.com/c/266/f/3834/index.rss
telegraph:
  name: The Telegraph
  category: News
  rss_feeds:
  - http://www.telegraph.co.uk/rss
  - http://www.telegraph.co.uk/news/rss
  - http://www.telegraph.co.uk/news/worldnews/rss
  - http://www.telegraph.co.uk/sport/rss
  - http://www.telegraph.co.uk/finance/rss
  - http://www.telegraph.co.uk/comment/rss
  - http://www.telegraph.co.uk/culture/rss
  - http://www.telegraph.co.uk/travel/rss
  - http://www.telegraph.co.uk/technology/rss
  - http://www.telegraph.co.uk/motoring/rss
nbcnews:
  name: NBC News
  category: News
  rss_feeds:
  - http://feeds.nbcnews.com/feeds/dailynightly
  - http://feeds.nbcnews.com/feeds/topstories
usatoday:
  name: USA Today
  category: News
  rss_feeds:
  - http://rssfeeds.usatoday.com/usatoday-NewsTopStories
  - http://rssfeeds.usatoday.com/UsatodaycomSports-TopStories
  - http://rssfeeds.usatoday.com/usatoday-LifeTopStories
  - http://rssfeeds.usatoday.com/UsatodaycomMoney-TopStories
  - http://rssfeeds.usatoday.com/usatoday-TechTopStories
  - http://rssfeeds.usatoday.com/UsatodaycomTravel-TopStories
  - http://ftw.usatoday.com/feed
womenshealthmag:
  name: Women's Health
  category: Entertainment
  rss_feeds:
  - http://www.womenshealthmag.com/washpofeed
ign:
  name: IGN.com
  rss_feeds: http://feeds.ign.com/ign/all
  category: Geek
gamespot:
  name: GameSpot
  category: Geek
  rss_feeds: http://www.gamespot.com/feeds/mashup/
n4g:
  name: N4G
  category: Geek
  rss_feeds:
  - http://n4g.com/rss/news?channel=&sort=latest
  - http://n4g.com/rss/news?channel=&sort=today
  - http://n4g.com/rss/news?channel=&sort=week
theescapist:
  name: The Escapist
  category: Geek
  rss_feeds:
  - http://www.escapistmagazine.com/rss/news
pcgamer:
  name: PC Gamer
  category: Geek
  rss_feeds: http://www.pcgamer.com/rss/
neoseeker:
  name: Neoseeker
  category: Geek
  rss_feeds:
  - http://www.neoseeker.com/feeds/news/?type=rss0.91
  - http://www.neoseeker.com/feeds/articles/?type=rss0.91
engadget:
  name: Engadget
  category: Geek
  rss_feeds:
  - http://www.engadget.com/rss.xml
  - http://www.engadget.com/tag/@gaming/rss.xml
gamesradar:
  name: GamesRadar
  category: Geek
  rss_feeds:
  - http://www.gamesradar.com/all-platforms/news/rss/
thoughtcatalog:
  name: Thought Catalog
  category: Hypersensational
  rss_feeds:
  - http://thoughtcatalog.com/feed/
elitedaily:
  name: Elite Daily
  category: Hypersensational
  rss_feeds: http://elitedaily.com/feed/
conservativehideout:
  name: Conservative Hideout
  category: Opinion - Conservative
  rss_feeds:
  - http://conservativehideout.com/feed/
twistedsifter:
  name: TwistedSifter
  category: Hypersensational
  rss_feeds:
  - http://twistedsifter.com/feed/
knowmore:
  name: Know More
  category: Hypersensational
  rss_feeds:
  - http://knowmore.washingtonpost.com/feed/
boingboing:
  name: Boing Boing
  category: Geek
  rss_feeds: http://boingboing.net/feed
