hackernews:
  name: Hacker News
  category: Geek
  default: false
theblaze:
  name: The Blaze
  category: Opinion - Conservative
  default: false
breitbart:
  name: Breitbart
  category: Opinion - Conservative
  default: false
alternet:
  name: Alternet
  category: Opinion - Progressive
  default: false
rawstory:
  name: The Raw Story
  category: Opinion - Progressive
  default: false
newsbusters:
  name: NewsBusters
  category: Opinion - Conservative
  default: false
faith_it:
  name: FaithIt
  category: Opinion - Conservative
  default: false
lifehacker:
  name: Lifehacker
  category: Geek
  default: false
daringfireball:
  name: Daring Fireball Links
  category: Geek
  default: false
macrumors:
  name: MacRumors
  category: Geek
  default: false
gizmodo:
  name: Gizmodo
  category: Geek
  default: false
valleywag:
  name: Valleywag
  category: Geek
  default: false
drudge_report:
  name: Drudge Report
  category: Opinion - Conservative
  default: false
free_republic:
  name: Free Republic
  category: Opinion - Conservative
  default: false
cns_news:
  name: CNS News
  category: Opinion - Conservative
  default: false
hot_air:
  name: HotAir
  category: Opinion - Conservative
  default: false
deadspin:
  name: Deadspin
  category: Sports
  default: false
sb_nation:
  name: SBNation
  category: Sports
  default: false
nypost:
  name: New York Post
  category: Opinion - Conservative
  default: false
huffpost_blogs:
  name: Huffington Post
  category: Opinion - Progressive
  default: false
thinkprogress:
  name: ThinkProgress
  category: Opinion - Progressive
  default: false
daily_kos:
  name: Daily Kos
  category: Opinion - Progressive
  default: false
distractify:
  name: Distractify
  category: Hypersensational
  default: false
mashable:
  name: Mashable
  category: Hypersensational
  default: false
sploid:
  name: Sploid
  category: Geek
  default: false
tmz:
  name: TMZ
  category: Entertainment
  default: false
giantbomb:
  name: Giant Bomb
  category: Geek
  default: false
kotaku:
  name: Kotaku
  category: Geek
  default: false
polygon:
  name: Polygon
  category: Geek
  default: false
buzzfeed:
  name: BuzzFeed
  category: Hypersensational
  default: true
pitchfork:
  name: Pitchfork
  category: Entertainment
  default: true
# Currently loads too slow
# billboard:
#   name: Billboard
#   category: Entertainment
#   default: false
spin:
  name: Spin
  category: Entertainment
  default: false
thegloss:
  name: The Gloss
  category: Misc.
  default: false
mommyish:
  name: Mommyish
  category: Misc.
  default: false
mcsweenys:
  name: McSweeny's
  category: Misc.
  default: false
av_club:
  name: The A.V. Club
  category: Entertainment
  default: true
hollywood_reporter:
  name: The Hollywood Reporter
  category: Entertainment
  default: false
college_humor:
  name: CollegeHumor
  category: Bro
  default: false
the_chive:
  name: The Chive
  category: Bro
  default: false
cracked:
  name: Cracked
  category: Hypersensational
  default: true
viralnova:
  name: Viralnova
  category: Hypersensational
  default: false
bro_bible:
  name: BroBible
  category: Bro
  default: false
zergnet:
  name: ZergNet
  category: Hypersensational
  default: true
upworthy:
  name: Upworthy
  category: Hypersensational
  default: true
gawker:
  name: Gawker
  category: Hypersensational
  default: false
defamer:
  name: Defamer
  category: Entertainment
  default: false
uproxx:
  name: Uproxx
  category: Entertainment
  default: false
hitfix:
  name: HitFix
  category: Entertainment
  default: false
mental_floss:
  name: Mental Floss
  category: Hypersensational
  default: false
jezebel:
  name: Jezebel
  category: Entertainment
  default: true
io9:
  name: io9
  category: Geek
  default: true
tested:
  name: Tested
  category: Geek
  default: false
cnn_blog:
  name: CNN
  category: News
  default: false
guardian_blogs:
  name: The Guardian
  category: News
  default: false
business_insider:
  name: Business Insider
  category: Hypersensational
  default: true
fivethirtyeight:
  name: FiveThirtyEight
  category: News
  default: false
nature_blog:
  name: Nature
  category: Geek
  default: false
npr_two_way:
  name: NPR Two Way
  category: News
  default: false
the_daily_beast:
  name: The Daily Beast
  category: News
  default: false
npr:
  name: NPR
  category: News
  default: false
nytimes:
  name: New York Times
  category: News
  default: true
r_politics:
  name: r/politics
  category: Reddit
  default: false
  dead: true
r_funny:
  name: r/funny
  category: Reddit
  default: false
  dead: true
wired:
  name: Wired
  category: Geek
  default: false
  url: http://wired.com
foxnews:
  name: Fox News
  category: Opinion - Conservative
  default: false
  url: http://www.foxnews.com/
nytimes_lede:
  name: New York Times Lede
  category: News
  default: false
  dead: true
