hackernews:
  name: Hacker News
  category: Tech
  default: false
theblaze:
  name: The Blaze
  category: Right-wing Opinion
  default: false
faith_it:
  name: FaithIt
  category: Right-wing Opinion
  default: false
lifehacker:
  name: Lifehacker
  category: Tech
  default: false
daringfireball:
  name: Daring Fireball Links
  category: Tech
  default: false
macrumors:
  name: MacRumors
  category: Tech
  default: false
gizmodo:
  name: Gizmodo
  category: Tech
  default: false
valleywag:
  name: Valleywag
  category: Tech
  default: false
drudge_report:
  name: Drudge Report
  category: Right-wing Opinion
  default: false
free_republic:
  name: Free Republic
  category: Right-wing Opinion
  default: false
cns_news:
  name: CNS News
  category: Right-wing Opinion
  default: false
hot_air:
  name: HotAir
  category: Right-wing Opinion
  default: false
deadspin:
  name: Deadspin
  category: Sports
  default: false
sb_nation:
  name: SBNation
  category: Sports
  default: false
nypost:
  name: New York Post
  category: Right-wing Opinion
  default: false
huffpost_blogs:
  name: Huffington Post Blogs
  category: Left-wing Opinion
  default: false
thinkprogress:
  name: ThinkProgress
  category: Left-wing Opinion
  default: false
daily_kos:
  name: Daily Kos
  category: Left-wing Opinion
  default: false
tmz:
  name: TMZ
  category: Entertainment
  default: false
giantbomb:
  name: Giant Bomb
  category: Games
  default: false
kotaku:
  name: Kotaku
  category: Games
  default: false
polygon:
  name: Polygon
  category: Games
  default: false
buzzfeed:
  name: BuzzFeed
  category: Trash
  default: true
pitchfork:
  name: Pitchfork
  category: Entertainment
  default: true
mcsweenys:
  name: McSweeny's
  category: Hipster
  default: false
av_club:
  name: The A.V. Club
  category: Entertainment
  default: true
college_humor:
  name: CollegeHumor
  category: Trash
  default: false
the_chive:
  name: The Chive
  category: Trash
  default: false
cracked:
  name: Cracked
  category: Trash
  default: true
bro_bible:
  name: BroBible
  category: Trash
  default: false
upworthy:
  name: Upworthy
  category: Trash
  default: true
gawker:
  name: Gawker
  category: Trash
  default: false
defamer:
  name: Defamer
  category: Entertainment
  default: false
uproxx:
  name: Uproxx
  category: Entertainment
  default: false
hitfix:
  name: HitFix
  category: Entertainment
  default: false
mental_floss:
  name: Mental Floss
  category: Trash
  default: false
jezebel:
  name: Jezebel
  category: Entertainment
  default: true
io9:
  name: io9
  category: Entertainment
  default: true
tested:
  name: Tested
  category: Tech
  default: false
cnn_blog:
  name: CNN News Blog
  category: News
  default: false
guardian_blogs:
  name: Guardian Blogs
  category: News
  default: false
business_insider:
  name: Business Insider
  category: News
  default: true
fivethirtyeight:
  name: FiveThirtyEight
  category: News
  default: false
nature_blog:
  name: Nature Blog
  category: Science
  default: false
npr_two_way:
  name: NPR Two Way
  category: News
  default: false
nytimes_lede:
  name: New York Times Lede
  category: News
  default: true
r_politics:
  name: r/politics
  category: Reddit
  default: false
r_funny:
  name: r/funny
  category: Reddit
  default: false
